#!/usr/bin/env bash

set -euo pipefail
set -x

test -d $HOME/var/run || mkdir -p $HOME/var/run
test -d $HOME/var/cache/agent-sandbox-squid || mkdir -p $HOME/var/cache/agent-sandbox-squid
test -d $HOME/var/log/agent-sandbox-squid || mkdir -p $HOME/var/log/agent-sandbox-squid

cp -v conf/agent-lockbox-squid.conf /tmp/agent-lockbox-squid.$$.conf
sed -i -e "s@HOME@$HOME@g" /tmp/agent-lockbox-squid.$$.conf

test -f $HOME/etc/allowed_domains.txt ||  -f install -m 644 conf/allowed_domains.txt $HOME/etc
test -f $HOME/etc/agent-lockbox-squid.conf || install -m 644 /tmp/agent-lockbox-squid.$$.conf $HOME/etc/agent-lockbox-squid.conf 
install -m 755 src/agent-lockbox-squid-proxy $HOME/bin
install -m 755 src/agent-lockbox $HOME/bin
install -m 755 src/agent-lockbox-notify-listener $HOME/bin
test -f $HOME/.config/systemd/user/agent-lockbox-squid.service || install -m 644 conf/agent-lockbox-squid.service $HOME/.config/systemd/user
test -f $HOME/.config/systemd/user/agent-notify-listener.service || install -m 644 conf/agent-lockbox-notify-listener.service $HOME/.config/systemd/user
systemctl --user daemon-reload
systemctl --user restart agent-lockbox-squid
systemctl --user restart agent-lockbox-notify-listener
