http_port 10385
acl allowed_domains dstdomain "HOME/etc/allowed_domains.txt"
http_access allow allowed_domains
http_access deny all
# Foreground + stdout logging
logfile_rotate 0
# access_log stdio:/dev/stdout
# cache_log stdio:/dev/stderr
cache_store_log none

pid_filename HOME/var/run/agent-shell-squid.pid
cache_dir ufs HOME/var/cache/agent-sandbox-squid 100 16 256
access_log stdio:HOME/var/log/agent-sandbox-squid/access.log
cache_log HOME/var/log/agent-sandbox-squid/cache.log
